import { CONFIG } from './config.js';

const app = document.querySelector('#app');
const audio = document.querySelector('#music');
const audioToggle = document.querySelector('#audioToggle');
let current = 0, timerHandle, typeHandle;
const name = CONFIG.herName;

const timerHTML = (label = 'Time since 15 March 2024') => `<div class="timer" data-timer><div class="time-box"><strong data-unit="years">00</strong><span>Years</span></div><div class="time-box"><strong data-unit="days">000</strong><span>Days</span></div><div class="time-box"><strong data-unit="hours">00</strong><span>Hours</span></div><div class="time-box"><strong data-unit="minutes">00</strong><span>Minutes</span></div><div class="time-box"><strong data-unit="seconds">00</strong><span>Seconds</span></div></div><p class="eyebrow">${label}</p>`;
const button = (text, action = 'next', cls = '') => `<button class="btn ${cls}" data-action="${action}">${text}</button>`;
const screen = (content, cls = '') => `<main class="screen ${cls}">${content}</main>`;

function render(i = current) {
  current = i; clearInterval(timerHandle); clearInterval(typeHandle);
  const pages = [
    screen(`<div class="eyebrow">A private little story</div><h1 class="display">Someone made<br>something special<br>for you<span class="accent">…</span></h1><p class="copy">For ${name}, with care.</p>${button('OPEN YOUR SURPRISE ♡','music')}`,'center'),
    screen(`<div class="eyebrow">19 September · for ${name}</div><h1 class="title">Happy Birthday, ${name} <span class="accent">♡</span></h1><p class="quote">Today isn't just another day…<br>Today is the day the most special person in my story was born.</p>${button('Continue →')}`,'center'),
    screen(`<div class="eyebrow">Chapter 01 · The beginning</div><h1 class="title">15 March 2024</h1><p class="quote">This is where my story with you began.</p><div class="memory-card"><p class="eyebrow">A quiet measure of us</p>${timerHTML('Time since I found you')}</div>${button('Open the next chapter →')}`,'center'),
    screen(`<div class="progress"><b>01</b> ─── 02 ─── 03 ─── 04 ─── 05</div><div class="eyebrow">The story, one door at a time</div><h1 class="title">Choose a chapter</h1><div class="chapters"><button class="chapter" data-action="beginning"><small>CHAPTER 01</small><span>The Beginning →</span></button><button class="chapter" data-action="closer"><small>CHAPTER 02</small><span>Getting Closer →</span></button><button class="chapter" data-action="gallery"><small>CHAPTER 03</small><span>Memories →</span></button><button class="chapter" data-action="today"><small>CHAPTER 04</small><span>Today →</span></button></div>`),
    screen(`<div class="eyebrow">Chapter 01 · The beginning</div><h1 class="title">The first page</h1><p class="copy typewriter" data-text="${escapeAttr(CONFIG.messages.beginning)}"></p>${button('Next memory →')}`),
    screen(`<div class="eyebrow">Chapter 02 · Getting closer</div><h1 class="title">Somewhere along the way</h1><p class="copy typewriter" data-text="${escapeAttr(CONFIG.messages.closer)}"></p>${button('Remember this? →')}`),
    screen(`<div class="eyebrow">A question from the story</div><h1 class="title">Do you remember the day we met?</h1><div class="actions">${button('YES ♡','rememberYes')}${button('NO…','rememberNo','ghost')}</div><div id="response"></div>`,'center'),
    screen(`<div class="eyebrow">Chapter 03 · Our first gallery memory</div><h1 class="title">Some moments deserve to be remembered forever.</h1><div class="gallery">${galleryHTML()}</div><p class="copy">Swipe through this little collection. Tap a photograph to keep it close.</p>${button('Next memory →')}`),
    screen(`<div class="eyebrow">A question for the future</div><h1 class="title">${name}, will you stay in my story for all the chapters that are yet to come?</h1><div class="actions">${button('YES ♡','stayYes')}${button('NO','stayNo','ghost')}</div><div id="response"></div>`,'center'),
    screen(`<div class="eyebrow">Chapter 04 · Today</div><h1 class="title">A few words for you</h1><p class="copy typewriter" data-text="${escapeAttr(CONFIG.messages.today)}"></p>${button('Open my letter →')}`),
    screen(`<div class="eyebrow">Written, slowly and sincerely</div><div class="letter"><h1 class="title">To ${name} <span class="accent">♡</span></h1><p class="copy typewriter" data-text="${escapeAttr(CONFIG.letter)}"></p><p class="copy">With love,<br>${CONFIG.myName}</p></div>${button('Walk through our years →')}`),
    screen(`<div class="eyebrow">Photo memory timeline</div><h1 class="title">The chapters we have kept</h1><div class="timeline">${timelineHTML()}</div>${button('One final chapter →')}`),
    screen(`<div class="eyebrow">The last page is not the end</div><h1 class="display">${name}<span class="accent">…</span></h1><h2 class="title">Happy Birthday <span class="accent">❤️</span></h2><p class="quote">You are one of the most beautiful chapters of my life.</p><p class="copy typewriter" data-text="${escapeAttr(CONFIG.finalMessage)}"></p>${button('One Last Thing →','final')}`,'center'),
    screen(`<div class="eyebrow">And still, the story continues</div><h1 class="title">Thank you for becoming a part of my story.</h1>${timerHTML('Time since 15 March 2024')}<p class="quote">And I'm still counting…</p><h2 class="title">Happy Birthday, ${name} <span class="accent">♡</span></h2><div class="qr"><img id="qr" alt="QR code for this surprise"></div><p class="copy">Scan this little doorway whenever you want to return.</p>`,'center')
  ];
  app.innerHTML = pages[i] || pages[0];
  if (i === 2 || i === 13) startTimer();
  typeText(); bindGallery();
}
function escapeAttr(s=''){return s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function galleryHTML(){return CONFIG.gallery.map((p,i)=>`<figure class="photo-card"><div class="placeholder" data-photo="${i}">${p.src ? `<img src="${p.src}" alt="${p.alt}" loading="lazy">` : p.alt}</div><figcaption>${p.caption||''}</figcaption></figure>`).join('')}
function timelineHTML(){return CONFIG.photoTimeline.map(p=>`<article class="timeline-item"><h3>${p.year}</h3><p class="eyebrow">${p.date}</p><p class="copy">${p.caption}</p>${p.src?`<img src="${p.src}" loading="lazy" alt="${p.caption}">`:''}</article>`).join('')}
function startTimer(){const start=new Date(CONFIG.relationshipStart);const update=()=>{let d=Math.max(0,Date.now()-start);let sec=Math.floor(d/1000);const seconds=sec%60;sec=Math.floor(sec/60);const minutes=sec%60;sec=Math.floor(sec/60);const hours=sec%24;const days=Math.floor(sec/24);const years=Math.floor(days/365.2425);const rest=Math.floor(days-years*365.2425);[['years',years],['days',rest],['hours',hours],['minutes',minutes],['seconds',seconds]].forEach(([u,v])=>{const el=document.querySelector(`[data-unit="${u}"]`);if(el)el.textContent=String(v).padStart(u==='days'?3:2,'0')})};update();timerHandle=setInterval(update,1000)}
function typeText(){const el=document.querySelector('.typewriter');if(!el)return;const text=el.dataset.text||'';let n=0;typeHandle=setInterval(()=>{el.textContent=text.slice(0,++n);if(n>=text.length)clearInterval(typeHandle)},24)}
function bindGallery(){document.querySelectorAll('.photo-card img').forEach(img=>img.addEventListener('click',()=>{const l=document.querySelector('#lightbox');l.hidden=false;l.querySelector('img').src=img.src}));const qr=document.querySelector('#qr');if(qr)qr.src='https://api.qrserver.com/v1/create-qr-code/?size=300x300&data='+encodeURIComponent(location.href)}
function response(html){const r=document.querySelector('#response');if(r)r.innerHTML=`<div class="memory-card" style="margin-top:28px"><p class="copy">${html}</p>${button('Continue →')}</div>`}
app.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='music'){if(CONFIG.songUrl){audio.src=CONFIG.songUrl;audio.play().catch(()=>{})}audioToggle.classList.remove('hidden');render(1);return}if(action==='rememberYes'){response('I knew you would remember. Some days simply stay with us forever.');return}if(action==='rememberNo'){response('Then I guess I have to remind you… 😭<br><br><span class="accent">15 March 2024 ♡</span>');return}if(action==='stayYes'){response('Then let’s keep writing it… one memory at a time.');return}if(action==='stayNo'){response('That button seems to be shy. Let’s try this again?');return}if(action==='final'){render(13);return}if(action==='beginning'){render(4);return}if(action==='closer'){render(5);return}if(action==='gallery'){render(7);return}if(action==='today'){render(9);return}render(current+1)});
audioToggle.addEventListener('click',()=>{if(audio.paused){audio.play().catch(()=>{});audioToggle.innerHTML='♫ <span>Music on</span>'}else{audio.pause();audioToggle.innerHTML='♫ <span>Music off</span>'}});document.querySelector('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox'||e.target.classList.contains('close-lightbox'))e.currentTarget.hidden=true});
render(0);
