import { CONFIG } from './config.js';
const app=document.querySelector('#app'), audio=document.querySelector('#music'), audioToggle=document.querySelector('#audioToggle'), lightbox=document.querySelector('#lightbox');
let page=0, timerHandle;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const btn=(label,action='next',cls='')=>`<button class="btn ${cls}" data-action="${action}">${label}</button>`;
const shell=(body,cls='')=>`<main class="screen ${cls}">${body}</main>`;
function timer(){return `<div class="timer"><div><b data-t="years">00</b><small>Years</small></div><div><b data-t="days">000</b><small>Days</small></div><div><b data-t="hours">00</b><small>Hours</small></div><div><b data-t="minutes">00</b><small>Minutes</small></div><div><b data-t="seconds">00</b><small>Seconds</small></div></div>`}
function media(m){return m.type==='video'?`<video class="chapter-media" controls playsinline preload="metadata" poster="${m.poster||''}"><source src="${m.src}" type="video/mp4"></video>`:`<img class="chapter-media clickable" src="${m.src}" alt="${esc(m.alt)}" loading="lazy">`}
function chapter(c){return shell(`<div class="chapter-top"><span>CHAPTER ${c.number}</span><span>${c.number} / 07</span></div><div class="eyebrow">${c.date}</div><h1 class="title">${c.title}</h1><p class="quote">${c.text}</p><div class="media-frame">${media(c.media)}</div>${c.number==='07'?`<p class="copy">This is for you — a virtual hug, because I am a little far from you right now, but soon we will be together.</p>`:''}${btn(c.number==='07'?'Ask me one last thing →':'Open Chapter '+String(Number(c.number)+1).padStart(2,'0')+' →')}`)}
function render(n=page){page=n;clearInterval(timerHandle);const c=CONFIG.chapters[n-2];let html;
if(n===0)html=shell(`<div class="eyebrow">A private little story</div><h1 class="display">Someone made<br>something special<br>for you<span class="accent">…</span></h1><p class="copy">For ${CONFIG.herName}, with care.</p>${btn('OPEN YOUR SURPRISE ♡','music')}`,'center');
else if(n===1)html=shell(`<div class="eyebrow">19 September · for ${CONFIG.herName}</div><h1 class="title">Happy Birthday, ${CONFIG.herName} <span class="accent">♡</span></h1><p class="quote">Today isn’t just another day…<br>Today is the day the most special person in my story was born.</p>${btn('Begin our seven chapters →')}`,'center');
else if(n===2)html=shell(`<div class="eyebrow">Our online story began</div><h1 class="title">15 March 2024</h1><p class="quote">The first hello became something I never wanted to lose.</p>${timer()}<p class="eyebrow">Time since our first chat</p>${btn('Open Chapter 01 →')}`,'center');
else if(n>=3&&n<=9)html=chapter(c);
else if(n===10)html=shell(`<div class="eyebrow">One last question, Baccha… 🥹</div><h1 class="title">These were only 7 chapters…</h1><p class="quote">Will you stay with me for every chapter still waiting to be written?</p><div class="actions">${btn('YES 💖','yes')}${btn('NO 🫶','no','ghost')}</div><div id="answer"></div>`,'center');
else html=shell(`<div class="eyebrow">The story continues</div><h1 class="display">Kirat<span class="accent">…</span></h1><p class="quote">I knew it… 🥹 Love you so much, Baccha. Now let’s write the rest of our story together. ♾️</p>${timer()}<p class="eyebrow">And I’m still counting</p><div class="hug-card"><img class="hug-gif" src="${CONFIG.hugGif}" alt="Virtual hug"></div><h2 class="title">Happy Birthday, Kirat <span class="accent">♡</span></h2>`,'center');
app.innerHTML=html;if(n===2||n===11)startTimer();bind();}
function startTimer(){const start=new Date(CONFIG.relationshipStart);const update=()=>{let s=Math.floor(Math.max(0,Date.now()-start)/1000),sec=s%60; s=Math.floor(s/60);let min=s%60; s=Math.floor(s/60);let hr=s%24;let days=Math.floor(s/24),years=Math.floor(days/365.2425),rest=Math.floor(days-years*365.2425);[['years',years],['days',rest],['hours',hr],['minutes',min],['seconds',sec]].forEach(([k,v])=>{const e=document.querySelector(`[data-t="${k}"]`);if(e)e.textContent=String(v).padStart(k==='days'?3:2,'0')})};update();timerHandle=setInterval(update,1000)}
function bind(){document.querySelectorAll('.clickable').forEach(img=>img.onclick=()=>{lightbox.hidden=false;lightbox.style.display='grid';lightbox.querySelector('img').src=img.src});const qr=document.querySelector('#qr');if(qr)qr.src='https://api.qrserver.com/v1/create-qr-code/?size=300x300&data='+encodeURIComponent(location.href)}
function answer(text){document.querySelector('#answer').innerHTML=`<div class="memory-card answer"><p class="copy">${text}</p>${btn('Continue →')}</div>`}
app.onclick=e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='music'){if(CONFIG.songUrl){audio.src=CONFIG.songUrl;audio.play().catch(()=>{})}audioToggle.classList.remove('hidden');render(1)}else if(a==='yes')answer('I knew it… 🥹 Love you so much, Baccha. Now let’s write the rest of our story together. ♾️');else if(a==='no')answer('Koi baat nahi… Because these 7 chapters were never the end. For me, they mean we’re together for all 7 lifetimes. ❤️♾️');else if(a==='next')render(page+1);else render(page+1)};
audioToggle.onclick=()=>{if(audio.paused){audio.play().catch(()=>{});audioToggle.innerHTML='♫ <span>Music on</span>'}else{audio.pause();audioToggle.innerHTML='♫ <span>Music off</span>'}};
lightbox.onclick=e=>{if(e.target===lightbox||e.target.classList.contains('close-lightbox')){lightbox.hidden=true;lightbox.style.display='none'}};render();
